name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: write 
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ python3-pip


    - name: Compile C++ code
      run: |        
        cmake .
        make

    - name: Run program
      run: ./main | tee program_output.txt

    - name: Upload program output
      uses: actions/upload-artifact@v4
      with:
        name: program-logs
        path: program_output.txt
