name: Leaderboard Generator

on:
  schedule:
    - cron: "0 * * * *"  
  workflow_dispatch:      

permissions:
  contents: write  

jobs:
  generate-leaderboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow

      - name: Generate leaderboard image
        run: |
          python leaderboard.py

      - name: Send leaderboard image to Telegram
        run: python send_leaderboard.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Commit and push leaderboard image
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add leaderboard.png
          git commit -m "Update leaderboard image" || echo "No changes to commit"
          git push
