name: Run main.cpp on push

on:
  push:
    branches:
      - main 

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++

      - name: Build program
        run: |
          cmake .
          make

      - name: Run program and save logs
        run: ./main | tee program_output.txt

      - name: Upload logs artifact
        uses: actions/upload-artifact@v4
        with:
          name: program-logs
          path: program_output.txt
